<select class="form-select" required value="{{ old('country_code') }}" name="country_code">
    <option disabled value="">--- Choose Country ---</option> 
    <option disabled value="AFG">Afghanistan</option> 
    <option disabled value="ALA">Åland Islands</option> 
    <option disabled value="ALB">Albania</option> 
    <option disabled value="DZA">Algeria</option> 
    <option disabled value="ASM">American Samoa</option> 
    <option disabled value="AND">Andorra</option> 
    <option disabled value="AGO">Angola</option> 
    <option disabled value="AIA">Anguilla</option> 
    <option disabled value="ATA">Antarctica</option> 
    <option disabled value="ATG">Antigua and Barbuda</option> 
    <option disabled value="ARG">Argentina</option> 
    <option disabled value="ARM">Armenia</option> 
    <option disabled value="ABW">Aruba</option> 
    <option disabled value="AUS">Australia</option> 
    <option disabled value="AUT">Austria</option> 
    <option disabled value="AZE">Azerbaijan</option> 
    <option disabled value="BHS">Bahamas</option> 
    <option disabled value="BHR">Bahrain</option> 
    <option disabled value="BGD">Bangladesh</option> 
    <option disabled value="BRB">Barbados</option> 
    <option disabled value="BLR">Belarus</option> 
    <option disabled value="BEL">Belgium</option> 
    <option disabled value="BLZ">Belize</option> 
    <option disabled value="BEN">Benin</option> 
    <option disabled value="BMU">Bermuda</option> 
    <option disabled value="BTN">Bhutan</option> 
    <option disabled value="BOL">Bolivia, Plurinational State of</option> 
    <option disabled value="BES">Bonaire, Sint Eustatius and Saba</option> 
    <option disabled value="BIH">Bosnia and Herzegovina</option> 
    <option disabled value="BWA">Botswana</option> 
    <option disabled value="BVT">Bouvet Island</option> 
    <option disabled value="BRA">Brazil</option> 
    <option disabled value="IOT">British Indian Ocean Territory</option> 
    <option disabled value="BRN">Brunei Darussalam</option> 
    <option disabled value="BGR">Bulgaria</option> 
    <option disabled value="BFA">Burkina Faso</option> 
    <option disabled value="BDI">Burundi</option> 
    <option disabled value="KHM">Cambodia</option> 
    <option disabled value="CMR">Cameroon</option> 
    <option disabled value="CAN">Canada</option> 
    <option disabled value="CPV">Cape Verde</option> 
    <option disabled value="CYM">Cayman Islands</option> 
    <option disabled value="CAF">Central African Republic</option> 
    <option disabled value="TCD">Chad</option> 
    <option disabled value="CHL">Chile</option> 
    <option disabled value="CHN">China</option> 
    <option disabled value="CXR">Christmas Island</option> 
    <option disabled value="CCK">Cocos (Keeling) Islands</option> 
    <option disabled value="COL">Colombia</option> 
    <option disabled value="COM">Comoros</option> 
    <option disabled value="COG">Congo</option> 
    <option disabled value="COD">Congo, the Democratic Republic of the</option>
    <option disabled value="COK">Cook Islands</option> 
    <option disabled value="CRI">Costa Rica</option> 
    <option disabled value="CIV">Côte d'Ivoire</option> 
    <option disabled value="HRV">Croatia</option> 
    <option disabled value="CUB">Cuba</option> 
    <option disabled value="CUW">Curaçao</option> 
    <option disabled value="CYP">Cyprus</option> 
    <option disabled value="CZE">Czech Republic</option> 
    <option disabled value="DNK">Denmark</option> 
    <option disabled value="DJI">Djibouti</option> 
    <option disabled value="DMA">Dominica</option> 
    <option disabled value="DOM">Dominican Republic</option> 
    <option disabled value="ECU">Ecuador</option> 
    <option disabled value="EGY">Egypt</option> 
    <option disabled value="SLV">El Salvador</option> 
    <option disabled value="GNQ">Equatorial Guinea</option> 
    <option disabled value="ERI">Eritrea</option> 
    <option disabled value="EST">Estonia</option> 
    <option disabled value="ETH">Ethiopia</option> 
    <option disabled value="FLK">Falkland Islands (Malvinas)</option> 
    <option disabled value="FRO">Faroe Islands</option> 
    <option disabled value="FJI">Fiji</option> 
    <option disabled value="FIN">Finland</option> 
    <option disabled value="FRA">France</option> 
    <option disabled value="GUF">French Guiana</option> 
    <option disabled value="PYF">French Polynesia</option> 
    <option disabled value="ATF">French Southern Territories</option> 
    <option disabled value="GAB">Gabon</option> 
    <option disabled value="GMB">Gambia</option> 
    <option disabled value="GEO">Georgia</option> 
    <option disabled value="DEU">Germany</option> 
    <option disabled value="GHA">Ghana</option> 
    <option disabled value="GIB">Gibraltar</option> 
    <option disabled value="GRC">Greece</option> 
    <option disabled value="GRL">Greenland</option> 
    <option disabled value="GRD">Grenada</option> 
    <option disabled value="GLP">Guadeloupe</option> 
    <option disabled value="GUM">Guam</option> 
    <option disabled value="GTM">Guatemala</option> 
    <option disabled value="GGY">Guernsey</option> 
    <option disabled value="GIN">Guinea</option> 
    <option disabled value="GNB">Guinea-Bissau</option> 
    <option disabled value="GUY">Guyana</option> 
    <option disabled value="HTI">Haiti</option> 
    <option disabled value="HMD">Heard Island and McDonald Islands</option> 
    <option disabled value="VAT">Holy See (Vatican City State)</option> 
    <option disabled value="HND">Honduras</option> 
    <option disabled value="HKG">Hong Kong</option> 
    <option disabled value="HUN">Hungary</option> 
    <option disabled value="ISL">Iceland</option> 
    <option disabled value="IND">India</option> 
    <option disabled value="IDN">Indonesia</option> 
    <option disabled value="IRN">Iran, Islamic Republic of</option> 
    <option disabled value="IRQ">Iraq</option> 
    <option disabled value="IRL">Ireland</option> 
    <option disabled value="IMN">Isle of Man</option> 
    <option disabled value="ISR">Israel</option> 
    <option disabled value="ITA">Italy</option> 
    <option disabled value="JAM">Jamaica</option> 
    <option disabled value="JPN">Japan</option> 
    <option disabled value="JEY">Jersey</option> 
    <option disabled value="JOR">Jordan</option> 
    <option disabled value="KAZ">Kazakhstan</option> 
    <option disabled value="KEN">Kenya</option> 
    <option disabled value="KIR">Kiribati</option> 
    <option disabled value="PRK">Korea, Democratic People's Republic of</option> 
    <option disabled value="KOR">Korea, Republic of</option> 
    <option disabled value="KWT">Kuwait</option> 
    <option disabled value="KGZ">Kyrgyzstan</option> 
    <option disabled value="LAO">Lao People's Democratic Republic</option> 
    <option disabled value="LVA">Latvia</option> 
    <option disabled value="LBN">Lebanon</option> 
    <option disabled value="LSO">Lesotho</option> 
    <option disabled value="LBR">Liberia</option> 
    <option disabled value="LBY">Libya</option> 
    <option disabled value="LIE">Liechtenstein</option> 
    <option disabled value="LTU">Lithuania</option> 
    <option disabled value="LUX">Luxembourg</option> 
    <option disabled value="MAC">Macao</option> 
    <option disabled value="MKD">North Macedonia</option> 
    <option disabled value="MDG">Madagascar</option> 
    <option disabled value="MWI">Malawi</option> 
    <option disabled value="MYS">Malaysia</option> 
    <option disabled value="MDV">Maldives</option> 
    <option disabled value="MLI">Mali</option> 
    <option disabled value="MLT">Malta</option> 
    <option disabled value="MHL">Marshall Islands</option> 
    <option disabled value="MTQ">Martinique</option> 
    <option disabled value="MRT">Mauritania</option> 
    <option disabled value="MUS">Mauritius</option> 
    <option disabled value="MYT">Mayotte</option> 
    <option disabled value="MEX">Mexico</option> 
    <option disabled value="FSM">Micronesia, Federated States of</option> 
    <option disabled value="MDA">Moldova, Republic of</option> 
    <option disabled value="MCO">Monaco</option> 
    <option disabled value="MNG">Mongolia</option> 
    <option disabled value="MNE">Montenegro</option> 
    <option disabled value="MSR">Montserrat</option> 
    <option disabled value="MAR">Morocco</option> 
    <option disabled value="MOZ">Mozambique</option> 
    <option disabled value="MMR">Myanmar</option> 
    <option disabled value="NAM">Namibia</option> 
    <option disabled value="NRU">Nauru</option> 
    <option disabled value="NPL">Nepal</option> 
    <option disabled value="NLD">Netherlands</option> 
    <option disabled value="NCL">New Caledonia</option> 
    <option disabled value="NZL">New Zealand</option> 
    <option disabled value="NIC">Nicaragua</option> 
    <option disabled value="NER">Niger</option> 
    <option disabled value="NGA">Nigeria</option> 
    <option disabled value="NIU">Niue</option> 
    <option disabled value="NFK">Norfolk Island</option> 
    <option disabled value="MNP">Northern Mariana Islands</option> 
    <option disabled value="NOR">Norway</option> 
    <option disabled value="OMN">Oman</option> 
    <option disabled value="PAK">Pakistan</option> 
    <option disabled value="PLW">Palau</option> 
    <option disabled value="PSE">Palestinian Territory, Occupied</option> 
    <option disabled value="PAN">Panama</option> 
    <option disabled value="PNG">Papua New Guinea</option> 
    <option disabled value="PRY">Paraguay</option> 
    <option disabled value="PER">Peru</option> 
    <option disabled value="PHL">Philippines</option> 
    <option disabled value="PCN">Pitcairn</option> 
    <option disabled value="POL">Poland</option> 
    <option disabled value="PRT">Portugal</option> 
    <option disabled value="PRI">Puerto Rico</option> 
    <option disabled value="QAT">Qatar</option> 
    <option disabled value="REU">Réunion</option> 
    <option disabled value="ROU">Romania</option> 
    <option disabled value="RUS">Russian Federation</option> 
    <option disabled value="RWA">Rwanda</option> 
    <option disabled value="BLM">Saint Barthélemy</option> 
    <option disabled value="SHN">Saint Helena, Ascension and Tristan da Cunha</option> 
    <option disabled value="KNA">Saint Kitts and Nevis</option> 
    <option disabled value="LCA">Saint Lucia</option> 
    <option disabled value="MAF">Saint Martin (French part)</option> 
    <option disabled value="SPM">Saint Pierre and Miquelon</option> 
    <option disabled value="VCT">Saint Vincent and the Grenadines</option> 
    <option disabled value="WSM">Samoa</option> 
    <option disabled value="SMR">San Marino</option> 
    <option disabled value="STP">Sao Tome and Principe</option> 
    <option disabled value="SAU">Saudi Arabia</option> 
    <option disabled value="SEN">Senegal</option> 
    <option disabled value="SRB">Serbia</option> 
    <option disabled value="SYC">Seychelles</option> 
    <option disabled value="SLE">Sierra Leone</option> 
    <option disabled value="SGP">Singapore</option> 
    <option disabled value="SXM">Sint Maarten (Dutch part)</option> 
    <option disabled value="SVK">Slovakia</option> 
    <option disabled value="SVN">Slovenia</option> 
    <option disabled value="SLB">Solomon Islands</option> 
    <option disabled value="SOM">Somalia</option> 
    <option disabled value="ZAF">South Africa</option> 
    <option disabled value="SGS">South Georgia and the South Sandwich Islands</option> 
    <option disabled value="SSD">South Sudan</option> 
    <option disabled value="ESP">Spain</option> 
    <option disabled value="LKA">Sri Lanka</option> 
    <option disabled value="SDN">Sudan</option> 
    <option disabled value="SUR">Suriname</option> 
    <option disabled value="SJM">Svalbard and Jan Mayen</option> 
    <option disabled value="SWZ">Swaziland</option> 
    <option disabled value="SWE">Sweden</option> 
    <option disabled value="CHE">Switzerland</option> 
    <option disabled value="SYR">Syrian Arab Republic</option> 
    <option disabled value="TWN">Taiwan, Province of China</option> 
    <option disabled value="TJK">Tajikistan</option> 
    <option value="TZA" selected>Tanzania, United Republic of</option> 
    <option disabled value="THA">Thailand</option> 
    <option disabled value="TLS">Timor-Leste</option> 
    <option disabled value="TGO">Togo</option> 
    <option disabled value="TKL">Tokelau</option> 
    <option disabled value="TON">Tonga</option> 
    <option disabled value="TTO">Trinidad and Tobago</option> 
    <option disabled value="TUN">Tunisia</option> 
    <option disabled value="TUR">Turkey</option> 
    <option disabled value="TKM">Turkmenistan</option> 
    <option disabled value="TCA">Turks and Caicos Islands</option> 
    <option disabled value="TUV">Tuvalu</option> 
    <option disabled value="UGA">Uganda</option> 
    <option disabled value="UKR">Ukraine</option> 
    <option disabled value="ARE">United Arab Emirates</option> 
    <option disabled value="GBR">United Kingdom</option> 
    <option disabled value="USA">United States</option> 
    <option disabled value="UMI">United States Minor Outlying Islands</option> 
    <option disabled value="URY">Uruguay</option> 
    <option disabled value="UZB">Uzbekistan</option> 
    <option disabled value="VUT">Vanuatu</option> 
    <option disabled value="VEN">Venezuela, Bolivarian Republic of</option> 
    <option disabled value="VNM">Viet Nam</option> 
    <option disabled value="VGB">Virgin Islands, British</option> 
    <option disabled value="VIR">Virgin Islands, U.S.</option> 
    <option disabled value="WLF">Wallis and Futuna</option> 
    <option disabled value="ESH">Western Sahara</option> 
    <option disabled value="YEM">Yemen</option> 
    <option disabled value="ZMB">Zambia</option> 
    <option disabled value="ZWE">Zimbabwe</option> 
  </select>